package ch.supsi.web.cardmarketplace.service;

import ch.supsi.web.cardmarketplace.model.Card;
import ch.supsi.web.cardmarketplace.repository.CardRepository;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;

import jakarta.persistence.criteria.Predicate;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class CardService {

    private final CardRepository cardRepository; // Inject CardRepository interface


    //--------------------------------------------------------
    // INJECT CardRepository INTERFACE TO APPLY CRUD METHODS
    //--------------------------------------------------------
    public CardService(CardRepository cardRepository) {
        this.cardRepository = cardRepository;
    }

    //-------------------
    // BASIC METHODS
    //-------------------

    public List<Card> getAllCards() {
        return cardRepository.findAll();
    }

    public Card addCard(Card card) {
        return cardRepository.save(card);
    }

    public Card updateCard(
            Long id,
            String name,
            String vendor,
            double price,
            String rarity,
            String condition,
            String collection,
            String description,
            String imagePath
    ) {
        Card card = cardRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Card not found"));

        card.setName(name);
        card.setVendor(vendor);
        card.setPrice(price);
        card.setRarity(rarity);
        card.setCardCondition(condition);
        card.setCollection(collection);
        card.setDescription(description);

        if (imagePath != null) {
            card.setImage(imagePath);
        }

        return cardRepository.save(card);
    }

    public Card getCardById(Long id) {
        return cardRepository.findById(id).orElse(null);
    }

    public void deleteCard(Long id) {
        cardRepository.deleteById(id);
    }

    // -------------------
    // PAGINATION
    // -------------------

    public List<Card> getLatest() {
        return cardRepository.findTop3ByOrderByCreatedDateDesc();
    }

    public List<Card> getPage(int offset, int limit) {

        int page = offset / limit;

        Pageable pageable = PageRequest.of(page, limit);

        return cardRepository.findAll(pageable).getContent();
    }

    // TOTALLY GENERATED BY AI: I have no idea what is bneing done here
    public Map<String, Object> searchPaged(
            int page,
            int size,
            String name,
            String vendor,
            List<String> collections,
            List<String> conditions,
            String rarity,
            String sort,
            String date
    ) {

        Sort sorting = Sort.unsorted();

        if (sort != null) {

            switch (sort) {

                case "price":
                    sorting = Sort.by("price").ascending();
                    break;

                case "date":
                    sorting = Sort.by("createdDate").descending();
                    break;

                case "rarity":
                    sorting = Sort.by("rarity").ascending();
                    break;
            }
        }

        Pageable pageable =
                PageRequest.of(page, size, sorting);

        Specification<Card> specification =
                withFilters(
                        name,
                        vendor,
                        collections,
                        conditions,
                        rarity,
                        date
                );

        Page<Card> result =
                cardRepository.findAll(specification, pageable);

        Map<String, Object> response = new HashMap<>();

        response.put("content", result.getContent());
        response.put("totalElements", result.getTotalElements());
        response.put("totalPages", result.getTotalPages());
        response.put("currentPage", result.getNumber());

        return response;
    }

    // HERE TOO: Gernerated by AI to supply searchPaged
    public static Specification<Card> withFilters(
            String name,
            String vendor,
            List<String> collections,
            List<String> conditions,
            String rarity,
            String date
    ) {

        return (root, query, cb) -> {

            Predicate predicate = cb.conjunction();

            if (name != null && !name.isBlank()) {
                predicate = cb.and(
                        predicate,
                        cb.like(
                                cb.lower(root.get("name")),
                                "%" + name.toLowerCase() + "%"
                        )
                );
            }

            if (vendor != null && !vendor.isBlank()) {
                predicate = cb.and(
                        predicate,
                        cb.like(
                                cb.lower(root.get("vendor")),
                                "%" + vendor.toLowerCase() + "%"
                        )
                );
            }

            if (collections != null && !collections.isEmpty()) {
                List<String> lowerCollections = collections.stream()
                        .map(String::toLowerCase)
                        .toList();
                predicate = cb.and(
                        predicate,
                        cb.lower(root.get("collection")).in(lowerCollections)
                );
            }

            if (conditions != null && !conditions.isEmpty()) {
                List<String> lowerConditions = conditions.stream()
                        .map(String::toLowerCase)
                        .toList();
                predicate = cb.and(
                        predicate,
                        cb.lower(root.get("cardCondition")).in(lowerConditions)
                );
            }

            if (rarity != null && !rarity.isBlank()) {
                predicate = cb.and(
                        predicate,
                        cb.equal(cb.lower(root.get("rarity")), rarity.toLowerCase())
                );
            }

            if (date != null && !date.isBlank()) {
                try {
                    java.time.LocalDate ld = java.time.LocalDate.parse(date);
                    java.time.LocalDateTime startOfDay = ld.atStartOfDay();
                    java.time.LocalDateTime endOfDay = ld.plusDays(1).atStartOfDay();
                    predicate = cb.and(
                            predicate,
                            cb.greaterThanOrEqualTo(root.get("createdDate"), startOfDay),
                            cb.lessThan(root.get("createdDate"), endOfDay)
                    );
                } catch (java.time.format.DateTimeParseException ex) {
                    // Ignore parse errors and don't apply date filter
                }
            }

            return predicate;
        };
    }
}
